// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PromotionsEngine.Application.CommandHandlers.Implementations.OrderCreatedCommandHandler.#ctor(PromotionsEngine.Domain.Repositories.Interfaces.ICustomerOrderRewardsLedgerRepository,Microsoft.Extensions.Logging.ILogger{PromotionsEngine.Application.CommandHandlers.Implementations.OrderCreatedCommandHandler},PromotionsEngine.Domain.Repositories.Interfaces.IMerchantRepository,PromotionsEngine.Domain.Repositories.Interfaces.IPromotionsRepository,PromotionsEngine.Domain.Repositories.Interfaces.IPromotionSummaryRepository,PromotionsEngine.Domain.Engines.RulesEngines.Interfaces.IPromotionRulesEngine,PromotionsEngine.Domain.Engines.RewardsEngines.Interfaces.IRewardsCalculationEngine,PromotionsEngine.Application.Interfaces.Managers.IServiceBusManager,Microsoft.Extensions.Options.IOptions{PromotionsEngine.Application.Configuration.ServiceBusOptions})")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PromotionsEngine.Application.CommandHandlers.Implementations.OrderCreatedCommandHandler.#ctor(PromotionsEngine.Domain.Repositories.Interfaces.ICustomerOrderRewardsLedgerRepository,PromotionsEngine.Domain.Repositories.Interfaces.IMerchantRepository,PromotionsEngine.Domain.Repositories.Interfaces.IPromotionsRepository,PromotionsEngine.Domain.Repositories.Interfaces.IPromotionSummaryRepository,PromotionsEngine.Domain.Engines.RulesEngines.Interfaces.IPromotionRulesEngine,PromotionsEngine.Domain.Engines.RewardsEngines.Interfaces.IRewardsCalculationEngine,PromotionsEngine.Application.Interfaces.Managers.IServiceBusManager,Microsoft.Extensions.Options.IOptions{PromotionsEngine.Application.Configuration.ServiceBusOptions})")]
[assembly: SuppressMessage("Major Code Smell", "S3928:Parameter names used into ArgumentException constructors should match an existing one ", Justification = "<Pending>", Scope = "member", Target = "~M:PromotionsEngine.Application.CommandHandlers.Implementations.OrderRefundedCommandHandler.HandleOrderRefundedCommand(PromotionsEngine.Application.Commands.OrderRefundedCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:PromotionsEngine.Application.CommandHandlers.Implementations.OrderCreatedCommandHandler.#ctor(PromotionsEngine.Domain.Repositories.Interfaces.ICustomerOrderRewardsLedgerRepository,PromotionsEngine.Domain.Repositories.Interfaces.IMerchantRepository,PromotionsEngine.Domain.Repositories.Interfaces.IPromotionsRepository,PromotionsEngine.Domain.Repositories.Interfaces.IPromotionSummaryRepository,PromotionsEngine.Domain.Engines.RulesEngines.Interfaces.IPromotionRulesEngine,PromotionsEngine.Domain.Engines.RewardsEngines.Interfaces.IRewardsCalculationEngine,PromotionsEngine.Application.Interfaces.Managers.IServiceBusManager,Microsoft.Extensions.Options.IOptions{PromotionsEngine.Application.Configuration.ServiceBusOptions},PromotionsEngine.Application.Cache.Interfaces.IRedisCacheManager,PromotionsEngine.Domain.Repositories.Interfaces.IMerchantRegexRepository)")]
